# Generated by Django 3.1.5 on 2021-05-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NobelPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('motivation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laureate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('born_country', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nobel_prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize.nobelprize')),
            ],
        ),
    ]
