# Generated by Django 3.1.5 on 2021-05-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0002_auto_20210526_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laureate',
            old_name='firt_name',
            new_name='firtname',
        ),
    ]
