# Generated by Django 3.1.5 on 2021-05-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0003_auto_20210527_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laureate',
            name='affiliation',
        ),
    ]
