# Generated by Django 3.1.5 on 2021-05-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0005_auto_20210527_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laureate',
            name='nobel_prize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prize.nobelprize'),
            preserve_default=False,
        ),
    ]
