# Generated by Django 3.1.5 on 2021-05-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0006_auto_20210527_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='laureate',
            name='affiliation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
