# Generated by Django 3.1.5 on 2021-05-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0007_laureate_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laureate',
            name='affiliation',
        ),
    ]
