# Generated by Django 3.1.5 on 2021-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0009_auto_20210528_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laureate',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
