# Generated by Django 3.1.5 on 2021-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0010_auto_20210528_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laureate',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
